### ISSUE TITLE
Files progress not showed during move operation

### ISSUE THREAD

**Issue by acidzab** [Johannes11833/rclone_python#22]
Hi,
i'm using the rclone wrapper into a script of mine for ease music uploading into my google drive through rclone.
I've choosen your wrapper because has a nice view about the upload progress but sadly most of the time i can't see the progress of single files.
Here's a screenshoot of my script running

![immagine](https://github.com/Johannes11833/rclone_python/assets/97306551/c1039be4-8dc3-4dd5-9386-4d7abe288134)

Thanks :)

**Comment by Johannes11833** [comment]
Hi there! 
What version of rclone are you on (`rclone version`)? I noticed a while back that older versions of rclone format the subprogresses differently which is why my regex patterns don't work here.

I just tested it again with the latest version of rclone `v1.63.1` and here subprogresses work as expected.
![grafik](https://github.com/Johannes11833/rclone_python/assets/24914225/a9d5b269-72e6-4d4e-8b06-c503d26bd19a)
Please also note that subprogresses are usually not shown for small files like images.

**Comment by acidzab** [comment]
Hi,
thanks for answering, sadly i've the latest version

![immagine](https://github.com/Johannes11833/rclone_python/assets/97306551/3364939c-0af9-4756-81a8-b74e273a24a3)

Yep my files are heavy because they're tracks mostly in flac

**Comment by Johannes11833** [comment]
Hmm that is really weird. Would be interesting to see the output when running the same move operation with rclone directly.

**Comment by acidzab** [comment]
This is the output i receive using directly rclone move with progress flag
![immagine](https://github.com/Johannes11833/rclone_python/assets/97306551/0216bf1a-8337-497f-bad0-1586097a01b9)

**Comment by Johannes11833** [comment]
Ahhh I think I found the issue: your file names include spaces. Fixed it

**Comment by acidzab** [comment]
Thanks Johannes, updated and it works now :)
